### PR TITLE
Use Windows image in CI for assembly signing

### PR DESCRIPTION
**Pull request by agnauck**

### CODE REVIEW

**Comment by raphaotten** [comment]
Thank you very much!

**Comment by agnauck** [comment]
Let me know if the new builds work for you

**Comment by raphaotten** [comment]
It works, yes. Thank you!

Sidenote: No signature would be totally fine for my usecase as well. Probably as for all other users, because nobody complained about the wrong signature so far. Only a failing signature verification created problems.

**Comment by agnauck** [comment]
okay, that's good feedback.

I have not looked into detail what was wrong before. My assumption was that the signature was missing completely when I started to switch the builds from windows CI to Linux CI.

I may consider then removing the signing and switch back to Linux CI in the future.

**Pull request merged**
